# Generated by Django 3.1 on 2020-10-04 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='watchlist',
        ),
    ]
